"""ajout auto revenu quotidien

Revision ID: 9262d04f72e6
Revises: 
Create Date: 2025-11-24 11:41:47.943503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9262d04f72e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investissement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_pay', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investissement', schema=None) as batch_op:
        batch_op.drop_column('last_pay')

    # ### end Alembic commands ###
