"""add image column

Revision ID: 9a8b6b251cd0
Revises: b53646cae1d6
Create Date: 2025-11-26 10:36:08.097185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8b6b251cd0'
down_revision = 'b53646cae1d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vlog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))
        batch_op.drop_column('preuve')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vlog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preuve', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
