"""Ajout dernier paiement

Revision ID: abc26687ff43
Revises: 9262d04f72e6
Create Date: 2025-11-24 14:08:36.768186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'abc26687ff43'
down_revision = '9262d04f72e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investissement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dernier_paiement', sa.DateTime(), nullable=True))
        batch_op.drop_column('last_pay')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investissement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_pay', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('dernier_paiement')

    # ### end Alembic commands ###
